baseURL = 'https://example.org/'    # domain name for site. hugo uses this to build absolute URLs
languageCode = 'en-us'
title = 'My Portfolio Site'          # Used in layouts

theme = 'docsite'
pygmentsUseClasses = true

[params]
  author = "Arthur Gname"
  description = "My portfolio site"

  gh_url = "https://api.github.com/users"
  gh_user = "rjseymour66"

[outputs]
section = ["HTML", "JSON", "RSS"]

[permalinks]
  posts = "posts/:year/:month/:slug"
  year = "/posts/:slug"
  month = "/posts/:slug"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"